[General]
# 深巷有喵的「Surge_Developer」配置优化版
# > 日期：2026-04-19
# > 版本：5.0.0
# 配置作者：https://github.com/Rabbit-Spec/Surge
# 适用版本：iOS/macOS的Surge 5

# > Wi-Fi助理
wifi-assist = true
# > IPv6 支持（默认关闭，如无特殊需求不应开启 IPv6，目前网络环境下 IPv6 只会带来问题。）
ipv6 = true
# > 跳过代理
skip-proxy = 192.168.0.0/24, 10.0.0.0/8, 172.16.0.0/12, 127.0.0.1, localhost, *.local
# > 排除简单主机名
exclude-simple-hostnames = true
# > 测试超时（秒）
test-timeout = 5
# > Internet 测试 URL
internet-test-url = http://connectivitycheck.platform.hicloud.com/generate_204
# > 代理测速 URL
proxy-test-url = http://connectivitycheck.gstatic.com/generate_204
# > DNS 服务器
dns-server = 223.5.5.5, 114.114.114.114
# > DoH 服务器（部分机场拥有自己的 DoH 来保证节点解析）
# encrypted-dns-server = 你机场的 DoH

[Proxy Group]
SmartProxy = select, "🇺🇸 美国家宽", "🇺🇸 美国节点", "🇭🇰 香港节点", "🇯🇵 日本节点", "🇸🇬 新加坡节点", "🇩🇪 德国节点", Proxy, DIRECT
Streaming = select, "🇺🇸 美国家宽", "🇺🇸 美国节点", "🇯🇵 日本节点", "🇭🇰 香港节点", "🇸🇬 新加坡节点", Proxy
EMBYStream = select, Proxy, "🇩🇪 德国节点", "🇺🇸 美国节点", "🇯🇵 日本节点", "🇭🇰 香港节点"
Finance = select, "🇺🇸 美国家宽", "🇺🇸 美国节点", Proxy, DIRECT
SmartAI = select, "🇺🇸 美国家宽", "🇺🇸 美国节点", "🇯🇵 日本节点", Proxy
Messaging = select, DIRECT, Proxy, "🇭🇰 香港节点", "🇯🇵 日本节点", "🇺🇸 美国节点", "🇩🇪 德国节点"
  
# > 外部节点
🇭🇰 香港节点 = smart, include-other-group=Proxy, update-interval=0, no-alert=0, hidden=0, include-all-proxies=0, policy-regex-filter=(🇭🇰)|(香港)|(Hong)|(HK)
🇺🇸 美国家宽 = fallback, include-other-group=Proxy, update-interval=0, no-alert=0, hidden=0, include-all-proxies=0， policy-regex-filter=US-R-
🇺🇸 美国节点 = smart, include-other-group=Proxy, update-interval=0, no-alert=0, hidden=0, include-all-proxies=0, policy-regex-filter=(🇺🇸)|(美国)|(States)|(US)
🇯🇵 日本节点 = smart, include-other-group=Proxy, update-interval=0, no-alert=0, hidden=0, include-all-proxies=0, policy-regex-filter=(🇯🇵)|(日本)|(Japan)|(JP)
🇩🇪 德国节点 = smart, include-other-group=Proxy, update-interval=0, no-alert=0, hidden=0, include-all-proxies=0, policy-regex-filter=(🇩🇪)|(德国)|(Germany)|(DE)
🇸🇬 新加坡节点 = smart, include-other-group=Proxy, update-interval=0, no-alert=0, hidden=0, include-all-proxies=0, policy-regex-filter=(🇸🇬)|(新加坡)|(Singapore)|(SG)

Proxy = select, policy-path=我的节点, update-interval=0, no-alert=0, hidden=0, include-all-proxies=0

[Rule]
RULE-SET,https://github.com/Blankwonder/surge-list/raw/master/blocked.list,SmartProxy
RULE-SET,https://raw.githubusercontent.com/QuixoticHeart/rule-set/refs/heads/ruleset/loon/apns.list,Messaging
RULE-SET,https://github.com/Blankwonder/surge-list/raw/master/cn.list,DIRECT
DOMAIN,apps.apple.com,SmartProxy
DOMAIN-SUFFIX,ls.apple.com,DIRECT // Apple Maps
DOMAIN-SUFFIX,store.apple.com,DIRECT // Apple Store Online
RULE-SET,SYSTEM,SmartProxy
RULE-SET,https://github.com/Blankwonder/surge-list/raw/master/apple.list,SmartProxy
# 以下规则将触发本地 DNS 解析
RULE-SET,LAN,DIRECT
GEOIP,CN,DIRECT
FINAL,Proxy,dns-failed
